### ISSUE TITLE
onCompleted no longer returns response from server

### ISSUE THREAD

**Issue by ptaunton** [angular-ui/ui-uploader#25]
As part of the changes for PR #22, callbacks to onCompleted no longer return the response from the server since the callback is now triggered when the byte upload is complete, not when the server has responded. We need to see the server response (both the response code and body content) from the upload.

I suspect it was a non-intentional side effect of the pull request - perhaps there should now be an additional callback of onCompletedUpload to handle the new case and the original onCompleted can be restored to its original function.

**Comment by PowerKiKi** [comment]
Indeed it was not intended to remove this use case. Would you contribute a PR for that?

**Comment by yanStartapp** [comment]
Hi,
At uploader.js:116 I changed 'xhr.upload.onload' to 'xhr.onload' and it fixed the issue

**Comment by rogemita** [comment]
what is the status of this issue? because it definitively doesn't work, thanks

**Comment by PowerKiKi** [comment]
Somebody need to dig in, understand why #22 was needed in the first place and contribute a PR.

**Comment by BrandonNoad** [comment]
👍 

This is definitely a breaking change.

**Comment by PowerKiKi** [comment]
I realized I might not have been clear earlier. By "somebody" I meant one of you guys, since there isn't any project member actively developing it, this project entirely rely on community contributions to evolve. I am here merely to merge PR.

**Comment by BrandonNoad** [comment]
I can put up a PR to fix this. I think it makes the most sense to restore the original behaviour e.g. onCompleted() and onCompletedAll() are called after the transfer is completed AND the server has responded. I will add a new callback that will be called after the upload completes successfully, but the server hasn't necessarily responded.

@edenzz Thoughts on this since you submitted PR #22?
